/* AUTOGENERATED, DO NOT EDIT DIRECTLY
 * See gtk-priv/README.md for more information
 *
 * This file is part of gtk-layer-shell
 *
 * Copyright © 2010 Intel Corporation
 * Copyright © 2021 gtk-priv/scripts/code.py
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef GDK_WAYLAND_SURFACE_CLASS_PRIV_H
#define GDK_WAYLAND_SURFACE_CLASS_PRIV_H

#include "common.h"

typedef struct _GdkWaylandSurfaceClass GdkWaylandSurfaceClass;

// Version ID 0
// Valid for GTK master
struct _GdkWaylandSurfaceClass_v3_0_0
{
  struct _GdkSurfaceClass_v3_0_0 parent_class;
};

// For internal use only
int gdk_wayland_surface_class_priv_get_version_id() {
  static int version_id = -1;
  
  if (version_id == -1) {
    gtk_priv_assert_gtk_version_valid();
    int combo = gtk_get_minor_version() * 1000 + gtk_get_micro_version();
  
    switch (combo) {
        break;
  
      default:
        gtk_priv_warn_gtk_version_may_be_unsupported();
    }
  
    {
      version_id = 0;
    }
  }
  
  return version_id;
}

// GdkWaylandSurfaceClass::parent_class

GdkSurfaceClass * gdk_wayland_surface_class_priv_get_parent_class_ptr(GdkWaylandSurfaceClass * self) {
  switch (gdk_wayland_surface_class_priv_get_version_id()) {
    case 0: return (GdkSurfaceClass *)&((struct _GdkWaylandSurfaceClass_v3_0_0*)self)->parent_class;
    default: g_error("Invalid version ID"); g_abort();
  }
}

#endif // GDK_WAYLAND_SURFACE_CLASS_PRIV_H
